config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  devise_for :users
  root 'home#index'

  resources :dashboard, only: [:index]

  resources :server_monitors do
    collection do
      get :update_monitor 
    end
  end
  
  mount ActionCable.server => '/cable'

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/server_monitor.rb
class ServerMonitor < ApplicationRecord
    has_and_belongs_to_many :server_versions
    has_paper_trail only: [:current_users, :enabled]
    validates :name, :url, presence: true 
    validates :name, :url, uniqueness: true
    validates_format_of :url, with: /\Ahttps:\/\/(\w+.){2,4}\z/, message: 'Ensure your url starts with https://' 

    scope :deleted, -> {
        PaperTrail::Version.
            where(event: 'destroy', item_type: 'ServerMonitor'). 
            joins("LEFT JOIN server_monitors ON item_id=server_monitors.id").
            where("server_monitors.id IS NULL"). 
            select("distinct versions.item_id, versions.created_at, *").order('versions.created_at DESC')
    }

    scope :is_enabled, -> {
        ServerMonitor.where(enabled: true)
    }

    scope :is_disabled, -> {
        ServerMonitor.where(enabled: false)
    }

    def is_updated?
        self.server_versions.exists?(latest: true)
    end

    def update_monitor 
        UpdateServerMonitorJob.perform_now(self)
    end

    def get_usercount_history
        userCount = {}
        self.versions.each do |v|
            data = v.reify 
            unless data.nil?
                userCount[data.updated_at] = data.current_users
            end
        end
        userCount
    end

    def get_max_usercount_history
        maxUserCount = {}
        self.versions.each do |v|
            temp = v.reify
            unless temp.nil?
                maxUserCount[v.created_at] = temp.current_users
            end
        end

        maxUserCount.empty? ? nil : maxUserCount.group_by_hour_of_day { |k, v| k }.map { |k, v| [k, v.map(&:last).max] }
    end
end

app/models/server_version.rb
class ServerVersion < ApplicationRecord
    has_and_belongs_to_many :server_monitors
    validates :name, presence: true 
    validates_format_of :name, with: /\A202[0-1].[0-1][0-9].([0-3][0-9]|[0-9])\z/ 
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :rememberable, :validatable, :trackable, :lockable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def after_sign_in_path_for(resource)
        stored_location_for(resource) || dashboard_index_path 
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    before_action :authenticate_user!

    def index
        @search = ServerMonitor.ransack(params[:q])
        @monitors = @search.result.includes(:server_versions)

        @userCountData = {}
        @monitors.each do |m|
            @userCountData[m.name] = m.current_users
        end

        @totalUserCounts = {}
        @monitors.each do |m|
            @totalUserCounts[m.name] = m.get_max_usercount_history
        end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @monitors = ServerMonitor.is_enabled.order! 'name ASC'

    @officialMonitor = ServerMonitor.where(official: true).first
  end
end

app/controllers/server_monitors_controller.rb
class ServerMonitorsController < ApplicationController
    before_action :set_monitor, only: [:show, :update, :update_monitor, :edit, :destroy]
    before_action :set_server_types, only: [:new, :create, :edit, :update]
    before_action :set_regions, only: [:new, :create, :edit, :update]
    before_action :authenticate_user!

    def index
    end

    def show
    end

    def new
        @monitor = ServerMonitor.new
    end

    def create
        @monitor = ServerMonitor.new monitor_params
        
        if @monitor.valid?
            @monitor.save
            flash[:success] = 'Server Monitor successfully created'
            redirect_to dashboard_index_path
        else
            flash[:error] = "Server Monitor creation failed: #{@monitor.errors.full_messages[0]}"
            render :new 
        end
    end

    def edit
    end

    def update
        if @monitor.update(monitor_params) 
            flash[:success] = 'Server Monitor successfully updated'
            redirect_to dashboard_index_path
        else
            flash[:error] = "Server Monitor creation failed: #{@monitor.errors.full_messages[0]}"
            render :edit 
        end
    end

    def destroy
        @monitor.destroy
        flash[:success] = "Successfully removed #{@monitor.name}"
        redirect_to dashboard_index_path
    end

    def update_monitor
        @monitor.update_monitor

        # TODO: Add more robust error handling here. Catch instances where .update_monitor returns errors
        flash[:success] = "Successfully pinged #{@monitor.name}"
        redirect_to dashboard_index_path
    end

    private

    def monitor_params 
        params.require(:server_monitor).permit(:name, :url, :description, :enabled, :region, :official)
    end

    def set_monitor
        @monitor = ServerMonitor.find(params[:id])
    end

    def set_server_types
        @server_types = {
            true: 'Official',
            false: 'Community'
        }
    end

    def set_regions
        @regions = {
            'North America': 'North America',
            'Oceania': 'Oceania',
            'Europe': 'Europe'
        }
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def printRegion(region, id)
        case region
        when "North America"
            "<i class='fas fa-globe-americas mr-1'></i><span id='region-#{id}'>NA</span>"
        when "Europe"
            "<i class='fas fa-globe-europe mr-1'></i><span id='region-#{id}'>EU</span>"
        when "Oceania"
            "<i class='fas fa-globe-asia mr-1'></i><span id='region-#{id}'>OCE</span>"
        else
            "Unknown"
        end
    end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/server_monitors_helper.rb
module ServerMonitorsHelper
end

app/views/dashboard/index.html.erb
<div id="header-overlay" class="container">
    <canvas id="dot-canvas" class="position-absolute"></canvas>
    
    <%= line_chart @totalUserCounts.map { |k, v| {name: k, data: v} }, 
        xtitle: 'Hour of Day', 
        ytitle: 'User Count', 
        library: { 
            backgroundColor: '', 
            legend: { textStyle: { color: '#17a2b8' } },
            vAxis: { textStyle: { color: '#17a2b8' }, titleTextStyle: { color: '#17a2b8' }, gridlines: { color: '' } },  
            hAxis: { textStyle: { color: '#17a2b8' }, titleTextStyle: { color: '#17a2b8' } } } %>

    <div class="card text-center bg-dark border-info m-3">
        <div class="card-header text-info">
        CrewLink Server List 
        </div>

        <div class="row m-0">
            <div class="col-md-2 p-1 text-left">
                <%= link_to new_server_monitor_path, class: "btn btn-sm btn-outline-info" do %>
                    <%= fa_icon 'plus' %>
                    New Monitor 
                <% end %>
            </div>

            <div class="col-md-10">
                <%= search_form_for @search, url: dashboard_index_path, class: "form-inline" do |f| %>
                    <%= f.search_field :name_or_url_cont, class: "form-control mr-1 ml-auto" %>
                    <%= button_tag type: "submit", class: "btn btn-sm btn-outline-info mr-1" do %>
                        <%= fa_icon "search" %> Search
                    <% end %>
                    <%= link_to dashboard_index_path, class: "btn btn-sm btn-outline-warning" do %>
                        <%= fa_icon "ban" %> Reset Search
                    <% end %>
                <% end %>
            </div>
        </div>

        <table class="table table-striped table-hover table-dark">
            <thead>
                <tr>
                    <th scope="col"><%= sort_link @search, :name, default_order: :desc %></th>
                    <th scope="col"><%= sort_link @search, :url, "URL" %></th>
                    <th scope="col"><%= sort_link @search, :official, "Server Type" %></th>
                    <th scope="col"><%= sort_link @search, :current_users, "Current Users" %></th>
                    <th scope="col"><%= sort_link @search, :region, "Region" %></th>
                    <th scope="col"><%= sort_link @search, :available, "Online" %></th>
                    <th scope="col"><%= sort_link @search, :enabled, "Enabled" %></th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                <% @monitors.each do |monitor| %>
                    <tr>
                        <td class="text-<%= monitor.available ? 'success' : 'danger' %>"><%= monitor.name %></td>
                        <td><%= monitor.url %></td>
                        <td><%= monitor.official ? 'Official' : 'Community' %></td>
                        <td><%= monitor.current_users %></td>
                        <td><%= monitor.region %></td>
                        <td><span class="badge badge-<%= monitor.available ? 'success' : 'danger' %>"><%= monitor.available ? 'Online' : 'Offline' %></span></td>
                        <td><span class="badge badge-<%= monitor.enabled ? 'success' : 'danger' %>"><%= monitor.enabled ? 'Enabled' : 'Disabled' %></span></td>
                        <td>
                            <%= link_to fa_icon('eye'), { controller: "server_monitors", action: "show", id: monitor.id }, { class: 'text-info', title: 'View Monitor', data: { toggle: 'tooltip', placement: 'right' } } %>
                            <%= link_to fa_icon('edit'), { controller: "server_monitors", action: "edit", id: monitor.id }, { class: 'text-info', title: 'Edit Monitor', data: { toggle: 'tooltip', placement: 'right' } } %>
                            <%= link_to fa_icon('sync'), { controller: "server_monitors", action: "update_monitor", id: monitor.id }, { class: 'text-info', title: 'Update Monitor', data: { toggle: 'tooltip', placement: 'right' } } %>
                            <%= link_to fa_icon('trash'), { controller: "server_monitors", action: "destroy", id: monitor.id }, { class: 'text-info', method: :delete, title: 'Delete Monitor', data: { toggle: 'tooltip', placement: 'right', confirm: "Are you sure you want to destroy #{monitor.name}?" } } %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/home/index.html.erb
<div id="header-overlay" class="container">
  <canvas id="dot-canvas" class="position-absolute"></canvas>
  <div class="card text-center bg-dark border-info m-3">
    <div class="card-header text-info">
      CrewLink Server List 
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-4 d-flex">
          <div id="outer-card-<%= @officialMonitor.id %>" class="card bg-dark border-<%= @officialMonitor.available ? 'info' : 'danger' %> m-3 <%= @officialMonitor.available ? 'hoverable' : '' %>">
            <div id="inner-card-<%= @officialMonitor.id %>" class="<%= @officialMonitor.available ? 'card-overlay' : 'card-offline-overlay' %> d-flex flex-column align-items-center justify-content-center">
              <a id="card-text-<%= @officialMonitor.id %>" href="<%= @officialMonitor.url %>" class="text-center w-100 text-<%= @officialMonitor.available ? 'info' : 'danger' %>">
                <% if @officialMonitor.available %>
                  <%= @officialMonitor.url %>
                <% else %>
                  OFFLINE
                <% end %>
              </a>
              <button id="copy-button-<%= @officialMonitor.id %>" class="cb-btn btn btn-sm btn-outline-<%= @officialMonitor.available ? 'info' : 'danger' %> mt-2" data-clipboard-text="<%= @officialMonitor.url %>"><i class="fas fa-copy"></i></button>
            </div>
            <div class="card-header text-<%= @officialMonitor.available ? 'info' : 'danger' %>">
              Official Server
            </div>
            <img class="card-img-top" src="https://github.com/ottomated/CrewLink/raw/master/logo.png" class="img-fluid" alt="CrewLink Logo">
            <div class="card-body">
              <h6 class="card-title text-<%= @officialMonitor.available ? 'info' : 'danger' %>">
                Ottomated 
                <br />
                <br /> 
                <i class="fas fa-user"></i> 
                <span id="userCount-<%= @officialMonitor.id %>"><%= @officialMonitor.current_users %></span>
              </h6>
            </div>
            <div class="card-footer">
              <small class="text-muted">Last Updated At: <%= @officialMonitor.updated_at %></small>
            </div>
          </div>
        </div>
        <div class="col-sm-12 col-md-12 col-lg-8">
          <div class="card text-center bg-dark border-warning m-3">
            <div class="card-header text-warning">
              Community Servers
            </div>
            <div class="card-body">
              <div class="card-columns">
                <% @monitors.each do |monitor| %>
                  <% unless monitor.official %>
                    <div id="outer-card-<%= monitor.id %>" class="card text-left bg-dark border-<%= monitor.available ? 'success' : 'danger' %> h-100 w-90 <%= monitor.available ? 'hoverable' : '' %>">
                      <div id="inner-card-<%= monitor.id %>" class="<%= monitor.available ? 'card-overlay' : 'card-offline-overlay' %> d-flex flex-column align-items-center justify-content-center">
                        <a id="card-text-<%= monitor.id %>" href="<%= monitor.url %>" class="text-center w-100 text-<%= monitor.available ? 'success' : 'danger' %>">
                          <% if monitor.available %>
                            <%= monitor.url %>
                          <% else %>
                            OFFLINE
                          <% end %>
                        </a>
                        <button id="copy-button-<%= monitor.id %>" class="cb-btn btn btn-sm btn-outline-<%= monitor.available ? 'success' : 'danger' %> mt-2" data-clipboard-text="<%= monitor.url %>"><i class="fas fa-copy"></i></button>
                      </div>
                      <div class="card-body text-info d-sm-flex align-items-center">
                        <h6 class="card-title m-0"><%= monitor.name %></h6>
                        <p class='card-text m-0 ml-auto'><%= sanitize printRegion(monitor.region, monitor.id) %></p>
                        <p class="card-text ml-2"><i class="fas fa-user"></i> <span id="userCount-<%= monitor.id %>"><%= monitor.current_users %></span></p>
                      </div>
                      <div class="card-footer">
                        <small class="text-muted">Last updated <%= time_ago_in_words(monitor.updated_at) %> ago</small>
                      </div>
                    </div>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrewLink Status</title>
    <link rel="icon" href="<%= image_url 'StatusLogo.png' %>" type="image/x-icon">
    <meta property="og:title" content="CrewLink Status">
    <meta property="og:description" content="Web application that tracks uptime and status of public CrewLink servers">
    <meta property="og:image" content="<%= image_url 'StatusLogo.png' %>">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/1.18.0/TweenLite.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/gsap/1.18.0/easing/EasePack.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js"></script>
  </head>

  <body>
    <% unless flash.empty? %>
      <script type="text/javascript">
        <% flash.each do |f| %>
          <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
          toastr['<%= type %>']('<%= f[1] %>');
        <% end %>
      </script>
    <% end %>

    <% if user_signed_in? %>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/">
          <%= image_tag "StatusLogo.png", alt: "CrewLink Status Logo", width: "30", height: "30" %>
        </a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item <%= 'active' if current_page?(root_path) %> ">
              <a class="nav-link" href="/"><%= fa_icon "home" %> Landing <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item <%= 'active' if current_page?(dashboard_index_path) %>">
              <a class="nav-link" href="/dashboard"><%= fa_icon "tools" %> Admin</a>
            </li>
            <li class="nav-item ">
              <a class="nav-link" href="/sidekiq"><%= fa_icon "chart-line" %> Sidekiq</a>
            </li>
          </ul>
          <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
            <li class="nav-item">
              <%= link_to fa_icon("sign-out-alt"), destroy_session_path(current_user), method: :delete, data: { confirm: "Are you sure?" }, class: "text-info" %>
            </li>
          </ul>
        </div>
      </nav>
    <% end %>

    <%= yield %>

    <footer class="landing-footer">
      <div class="container">
          <div class="row">
              <div class="col-sm-4">
                  <ul class="social-networks text-left">
                    <li><a target="_blank" href="https://github.com/Cobchise" rel="noopener"> <i class="fab fa-lg fa-github fa-fw"></i> </a></li>
                    <li><a target="_blank" href="https://twitter.com/cobchise_sec" rel="noopener"> <i class="fab fa-lg fa-twitter fa-fw"></i> </a></li>
                    <li><a target="_blank" href="https://twitch.tv/Cobchise" rel="noopener"> <i class="fab fa-lg fa-twitch fa-fw"></i> </a></li>
                    <li class="text-muted">Cobchise</li>
                  </ul>
              </div>
              <div class="col-sm-4 text-muted text-center copyright">
                  Copyright <i class="far fa-copyright"></i> Cobchise - All Rights Reserved.
              </div>
              <div class="col-sm-4">
                  <ul class="social-networks text-right p-0 pr-5">
                    <li class="text-muted">Ottomated</li>
                    <li><a target="_blank" href="https://twitch.tv/Ottomated" rel="noopener"> <i class="fab fa-lg fa-twitch fa-fw"></i> </a></li>
                    <li><a target="_blank" href="https://twitter.com/ottomated_" rel="noopener"> <i class="fab fa-lg fa-twitter fa-fw"></i> </a></li>
                    <li><a target="_blank" href="https://github.com/Ottomated" rel="noopener"> <i class="fab fa-lg fa-github fa-fw"></i> </a></li>
                  </ul>
              </div>
          </div>
      </div>
    </footer>
  </body>
</html>

app/views/server_monitors/edit.html.erb
<div id="header-overlay" class="container pt-3">
    <canvas id="dot-canvas" class="position-absolute"></canvas>

    <div class="row align-items-center h-100">
    <div class="col-md-6 offset-md-3">
    <%= form_for @monitor, html: { class: 'form-signin card bg-dark border-info text-info p-0' } do |f| %>
        <div class="card-header text-info text-center">
        New Server Monitor 
        </div>

        <div class="form-label-group m-3">
            <%= f.text_field :name, autofocus: true, class: "form-control", required: true, placeholder: "Name (Cobchise)" %>
            <%= f.label :name, "Name (Cobchise)" %>
        </div>

        <div class="form-label-group m-3">
            <%= f.text_field :url, class: "form-control", required: true, placeholder: "URL (https://crewlink.among-us.tech)" %>
            <%= f.label :url, "URL (https://)" %>
        </div>

        <div class="form-label-group m-3">
            <%= f.text_field :description, class: "form-control", placeholder: "Description (Cobchise's CrewLink Server)" %>
            <%= f.label :description, "Description (Cobchise's Server)" %>
        </div>

        <div class="checkbox m-3">
            <%= f.check_box :enabled %>
            <%= f.label :enabled %>
        </div>

        <div class="form-label m-3">
            <%= f.label :region %>
            <%= f.collection_select :region, @regions, :first, :last, { include_blank: false, selected: @monitor.region }, class: "form-control" %>
        </div>

        <div class="form-group m-3">
            <%= f.label :official, "Server Type" %>
            <%= f.collection_select :official, @server_types, :first, :last, { include_blank: false, selected: @monitor.official }, class: "form-control" %>
        </div>

        <%= f.submit "Submit", class: "btn btn-lg btn-outline-info m-3" %>
    <% end %>
    </div>
    </div>
</div>

app/views/server_monitors/new.html.erb
<div id="header-overlay" class="container pt-3">
    <canvas id="dot-canvas" class="position-absolute"></canvas>

    <div class="row align-items-center h-100">
    <div class="col-md-6 offset-md-3">
    <%= form_for @monitor, html: { class: 'form-signin card bg-dark border-info text-info p-0' } do |f| %>
        <div class="card-header text-info text-center">
        New Server Monitor 
        </div>

        <div class="form-label-group m-3">
            <%= f.text_field :name, autofocus: true, class: "form-control", required: true, placeholder: "Name (Cobchise)" %>
            <%= f.label :name, "Name (Cobchise)" %>
        </div>

        <div class="form-label-group m-3">
            <%= f.text_field :url, class: "form-control", required: true, placeholder: "URL (https://crewlink.among-us.tech)" %>
            <%= f.label :url, "URL (https://)" %>
        </div>

        <div class="form-label-group m-3">
            <%= f.text_field :description, class: "form-control", placeholder: "Description (Cobchise's CrewLink Server)" %>
            <%= f.label :description, "Description (Cobchise's Server)" %>
        </div>

        <div class="checkbox m-3">
            <%= f.check_box :enabled %>
            <%= f.label :enabled %>
        </div>

        <div class="form-label m-3">
            <%= f.label :region %>
            <%= f.collection_select :region, @regions, :first, :last, { include_blank: false, selected: @monitor.region }, class: "form-control" %>
        </div>

        <div class="form-group m-3">
            <%= f.label :official, "Server Type" %>
            <%= f.collection_select :official, @server_types, :first, :last, { include_blank: false, selected: @monitor.official }, class: "form-control" %>
        </div>

        <%= f.submit "Submit", class: "btn btn-lg btn-outline-info m-3" %>
    <% end %>
    </div>
    </div>
</div>

app/views/server_monitors/show.html.erb
<div id="header-overlay" class="container pt-3">
    <canvas id="dot-canvas" class="position-absolute"></canvas>

    <div class="card bg-dark border-info text-info">
        <div class="card-header text-center">
            <%= @monitor.name %>
        </div>

        <div class="card-body p-3">
            <%= line_chart @monitor.get_usercount_history, xtitle: 'Time', ytitle: 'User Count', colors: ['#17a2b8', '#17a2b8'], library: { 
                backgroundColor: '', 
                vAxis: { textStyle: { color: '#17a2b8' }, titleTextStyle: { color: '#17a2b8' }, gridlines: { color: '' } },  
                hAxis: { textStyle: { color: '#17a2b8' }, titleTextStyle: { color: '#17a2b8' } } } %>
        </div>
    </div>
</div>